End early

diff --git a/.github/actions/setup-kat/action.yml b/.github/actions/setup-kat/action.yml
--- a/.github/actions/setup-kat/action.yml
+++ b/.github/actions/setup-kat/action.yml
@@ -34,4 +34,4 @@ runs:
         echo "Current PATH: $PATH"
         ls -l "$kat_binary_path"
 
-        echo "Installed kat version $(kat version)"
+        echo "Installed kat version $(kat version)" || (echo "Failed to execute kat command" && exit 1)
